apiVersion: v1
kind: Service
metadata:
  name: crush-user
spec:
  selector:
    app: crush-user
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crush-user-mysql
spec:
  selector:
    app: crush-user
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
